site_name: Learn Engine Dev
repo_url: https://github.com/Chukobyte/learn-engine-dev
edit_uri: ""
site_description: Learn Engine Dev is tutorial series for developing a cross platform game engine from scratch.
site_author: Chukobyte
copyright: 'Copyright &copy; 2021 Chukobyte'

google_analytics:
  - "G-7S3213MH0R"
  - "auto"

plugins:
  - search
  - mermaid2

theme:
  name: material
  custom_dir: 'docs/theme'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Introduction: index.md
  - 1. Foundation:
    - Embedding Python:
        - Hello Python: foundation/embedding_python/hello_python.md
        - Embedding Further: foundation/embedding_python/embedding_further.md
        - Custom Python Module: foundation/embedding_python/custom_python_module.md
    - Game Loop & SDL:
        - Game Loop Introduction: foundation/game_loop_and_sdl/game_loop_introduction.md
        - Initialize SDL: foundation/game_loop_and_sdl/initialize_sdl.md
    - OpenGL Rendering:
        - Asset Management: foundation/opengl_rendering/asset_management.md
        - Rendering Sprites: foundation/opengl_rendering/rendering_sprites.md
        - Rendering Text: foundation/opengl_rendering/rendering_text.md
    - Implementing Audio:
        - Using SDL_mixer: foundation/implementing_audio/using_sdl_mixer.md
    - Input Management:
        - Input Events: foundation/input_management/input_events.md
        - Input Management: foundation/input_management/input_management.md
    - Entity Component System:
        - Building An ECS: foundation/entity_component_system/building_an_ecs.md
    - Serializing With JSON:
        - Parsing JSON Properties File: foundation/serializing_with_json/parsing_json_properties_file.md
        - Creating Scene Json Files: foundation/serializing_with_json/creating_scene_json_files.md
  - 2. Engine API:
      - About: engine_api/about.md
  - 3. Games:
      - About: games/about.md
  - Source Code: source_code/source_code.md

