site_name: Learn Engine Dev
repo_url: https://github.com/Chukobyte/learn-engine-dev
edit_uri: ""
site_description: Learn Engine Dev is tutorial series for developing a cross platform game engine from scratch.
site_author: Chukobyte
copyright: 'Copyright &copy; 2021 Chukobyte'

google_analytics:
  - "G-7S3213MH0R"
  - "auto"

plugins:
  - search
  - mermaid2

theme:
  name: material
  custom_dir: 'docs/theme'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Introduction: index.md
  - Embedding Python:
      - Hello Python: embedding_python/hello_python.md
      - Embedding Further: embedding_python/embedding_further.md
      - Custom Python Module: embedding_python/custom_python_module.md
  - Game Loop & SDL:
      - Game Loop Introduction: game_loop_and_sdl/game_loop_introduction.md
      - Initialize SDL: game_loop_and_sdl/initialize_sdl.md
  - OpenGL Rendering:
      - Asset Management: opengl_rendering/asset_management.md
      - Rendering Sprites: opengl_rendering/rendering_sprites.md
      - Rendering Text: opengl_rendering/rendering_text.md
  - Implementing Audio:
      - Using SDL_mixer: implementing_audio/using_sdl_mixer.md
  - Input Management:
      - Input Events: input_management/input_events.md
      - Input Management: input_management/input_management.md
  - Entity Component System:
      - Building An ECS: entity_component_system/building_an_ecs.md
  - Serializing With JSON:
      - Parsing JSON Properties File: serializing_with_json/parsing_json_properties_file.md
      - Creating Scene Json Files: serializing_with_json/creating_scene_json_files.md
  - Source Code: source_code/source_code.md

