site_name: Learn Engine Dev

nav:
  - Introduction: index.md
  - Getting Started:
      - Embedding Python: getting_started/embedding_python.md
  - Source Code: source_code/source_code.md

plugins:
  - search
  - mermaid2

theme: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
