site_name: Learn Engine Dev
repo_url: https://github.com/Chukobyte/learn-engine-dev
edit_uri: ""
site_description: Learn Engine Dev is tutorial series for developing a cross platform game engine from scratch.
site_author: Chukobyte
copyright: 'Copyright &copy; 2021 Chukobyte'

google_analytics:
  - "G-7S3213MH0R"
  - "auto"

plugins:
  - search
  - mermaid2

theme:
  name: material
  custom_dir: 'docs/theme'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Introduction: index.md
  - 1. Foundation:
    - Embedding Python:
        - Hello Python: 1.foundation/1.embedding_python/hello_python.md
        - Embedding Further: 1.foundation/1.embedding_python/embedding_further.md
        - Custom Python Module: 1.foundation/1.embedding_python/custom_python_module.md
    - Game Loop & SDL:
        - Game Loop Introduction: 1.foundation/2.game_loop_and_sdl/game_loop_introduction.md
        - Initialize SDL: 1.foundation/2.game_loop_and_sdl/initialize_sdl.md
    - OpenGL Rendering:
        - Asset Management: 1.foundation/3.opengl_rendering/asset_management.md
        - Rendering Sprites: 1.foundation/3.opengl_rendering/rendering_sprites.md
        - Rendering Text: 1.foundation/3.opengl_rendering/rendering_text.md
    - Implementing Audio:
        - Using SDL_mixer: 1.foundation/4.implementing_audio/using_sdl_mixer.md
    - Input Management:
        - Input Events: 1.foundation/5.input_management/input_events.md
        - Input Management: 1.foundation/5.input_management/input_management.md
    - Entity Component System:
        - Building An ECS: 1.foundation/6.entity_component_system/building_an_ecs.md
        - Managers: 1.foundation/6.entity_component_system/managers.md
        - ECS Orchestrator: 1.foundation/6.entity_component_system/ecs_orchestrator.md
    - Serializing With JSON:
        - Parsing JSON Properties File: 1.foundation/7.serializing_with_json/parsing_json_properties_file.md
        - Creating Scene Json Files: 1.foundation/7.serializing_with_json/creating_scene_json_files.md
    - Animations:
        - Animation System: 1.foundation/8.animations/animation_system.md
    - Collisions:
        - Collision System: 1.foundation/9.collisions/collision_system.md
  - 2. Engine API:
      - Defining Red Engine API: 2.engine_api/about.md
  - 3. Games:
      - Making Games: 3.games/about.md
  - Source Code: source_code/source_code.md

