site_name: Learn Engine Dev

nav:
  - Introduction: index.md
  - Embedding Python:
      - Hello Python: embedding_python/hello_python.md
      - Embedding Further: embedding_python/embedding_further.md
  - OpenGL Rendering:
      - Creating A Renderer: opengl_rendering/creating_a_renderer.md
  - Implementing Audio:
      - Using SDL_mixer: implementing_audio/using_sdl_mixer.md
  - Serializing With JSON:
      - Parsing JSON: serializing_with_json/parsing_json.md
  - Entity Component System:
      - Building An ECS: entity_component_system/building_an_ecs.md
  - Source Code: source_code/source_code.md

plugins:
  - search
  - mermaid2

theme: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
