site_name: Learn Engine Dev

nav:
  - Introduction: index.md
  - Embedding Python:
      - Hello Python: embedding_python/hello_python.md
      - Embedding Further: embedding_python/embedding_further.md
  - Source Code: source_code/source_code.md

plugins:
  - search
  - mermaid2

theme: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
